
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_0_RDWR_MODE34_MSELECT_DEVICE_ID,
		XPAR_AXI_GPIO_0_RDWR_MODE34_MSELECT_BASEADDR,
		XPAR_AXI_GPIO_0_RDWR_MODE34_MSELECT_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_0_RDWR_MODE34_MSELECT_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_2492_RDWR_NUM_DEVICE_ID,
		XPAR_AXI_GPIO_2492_RDWR_NUM_BASEADDR,
		XPAR_AXI_GPIO_2492_RDWR_NUM_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_2492_RDWR_NUM_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_DMA_RECEIVE_RDY_DEVICE_ID,
		XPAR_AXI_GPIO_DMA_RECEIVE_RDY_BASEADDR,
		XPAR_AXI_GPIO_DMA_RECEIVE_RDY_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_DMA_RECEIVE_RDY_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_DEBUG_DEVICE_ID,
		XPAR_AXI_GPIO_DEBUG_BASEADDR,
		XPAR_AXI_GPIO_DEBUG_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_DEBUG_IS_DUAL
	}
};


